#!/usr/bin/nft -f
# vim:set ts=2 sw=2 et:

define wg_if = "wg-client0"
define wg_endpoint = 5.44.252.67
define wg_port = 55830

table inet filter
delete table inet filter

table inet filter {
  chain input {
    type filter hook input priority filter
    policy drop

    ct state invalid drop comment "early drop of invalid connections"
    ct state {established, related} accept comment "allow tracked connections"

    iifname lo accept comment "allow from loopback"

    ip protocol icmp accept comment "allow icmp"
    meta l4proto ipv6-icmp accept comment "allow icmp v6"

    # Если нужен SSH доступ к этой машине, раскомментировать:
    # tcp dport ssh accept comment "allow sshd"

    # DHCP reply, полезно если интерфейс получает адрес по DHCP
#    udp sport 67 udp dport 68 accept comment "allow dhcp replies"

    pkttype host limit rate 5/second counter reject with icmpx type admin-prohibited
    counter
  }

  chain output {
    type filter hook output priority filter
    policy drop

    ct state invalid drop comment "drop invalid output"
    ct state {established, related} accept comment "allow tracked output"

    oifname lo accept comment "allow loopback"

    # Разрешить локальные адреса самой машины
    fib daddr type local accept comment "allow local addresses"

    # Разрешить сам WireGuard UDP-трафик к серверу
    ip daddr $wg_endpoint udp dport $wg_port accept comment "allow wireguard endpoint"

    # DHCP request, если внешний интерфейс получает адрес по DHCP
    udp sport 68 udp dport 67 accept comment "allow dhcp requests"

	ip daddr 192.168.10.1 tcp dport { 22, 8080 } accept
	ip daddr 192.168.10.160 accept
	ip daddr 192.168.2.200 accept
	ip daddr 192.168.10.1 drop

    # Если нужен доступ к локальной сети мимо VPN, раскомментировать нужное:
	ip daddr 192.168.10.0/24 accept comment "allow LAN"
#    ip daddr 192.168.0.0/16 accept comment "allow LAN"
#    ip daddr 10.0.0.0/8 accept comment "allow private LAN"
#    ip daddr 172.16.0.0/12 accept comment "allow private LAN"

    # Всё остальное разрешать только через WireGuard
    oifname $wg_if accept comment "allow traffic through WireGuard"

    counter reject with icmpx type admin-prohibited comment "killswitch: block non-WireGuard output"
  }

  chain forward {
    type filter hook forward priority filter
    policy drop
  }
}
