#!/bin/bash
# Network speed stuff stolen from http://linuxclues.blogspot.sg/2009/11/shell-script-show-network-speed.html

print_cpu() {
	echo -e "CPU:$(top -b -n1 | grep "Cpu(s)" | awk '{print $2 + $4}')%"
}


print_layout() {
	case "$(xset -q | grep LED | awk '{ print $10 }')" in
	  "0000000"[0-3]) KBD="En" ;;
	  "0000100"[0-3]) KBD="Ru" ;;
	  *) KBD="unknown" ;;
	esac

	echo -e "$KBD"
}


print_wifi() {
	ip=$(ip route get 8.8.8.8 2>/dev/null|grep -Eo 'src [0-9.]+'|grep -Eo '[0-9.]+')
	if=wlp4s0
		while IFS=$': \t' read -r label value
		do
			case $label in SSID) SSID=$value
				;;
			signal) SIGNAL=$value
				;;
		esac
	done < <(iw "$if" link)
	echo -e "$SSID $SIGNAL $ip"
}

print_mem(){
#	echo $(($(grep -m1 'MemAvailable:' /proc/meminfo | awk '{print $2}') / 1024))
	FREE_DATA=`free -m | grep Mem`
	CURRENT=`echo $FREE_DATA | cut -f3 -d' '`
	TOTAL=`echo $FREE_DATA | cut -f2 -d' '`
	echo "RAM:$(echo "scale = 2; $CURRENT/$TOTAL*100" | bc)%"
}


print_hdd(){
	echo "HDD:$(df -lh | awk '{if ($6 == "/") { print $5 }}' | head -1 | cut -d'%' -f1)%"
}


print_network(){
	logfile=/dev/shm/netlog
	[ -f "$logfile" ] || echo "0 0" > "$logfile"
	read -r rxprev txprev < "$logfile"
	rxcurrent="$(($(paste -d '+' /sys/class/net/[wl]*/statistics/rx_bytes)))"
	txcurrent="$(($(paste -d '+' /sys/class/net/[wl]*/statistics/tx_bytes)))"
	echo "D:$(bc <<< "scale=2; ($rxcurrent-$rxprev) / 10^6")" "U:$(bc <<< "scale=2; ($txcurrent-$txprev) / 10^6")"
	echo "$rxcurrent $txcurrent" > "$logfile"
}

print_temp(){
#	[ -f /sys/devices/platform/thinkpad_hwmon/hwmon/hwmon?/temp1_input ] && echo "$(head -c 2 /sys/devices/platform/thinkpad_hwmon/hwmon/hwmon?/temp1_input)℃"
#	test -f /sys/class/thermal/thermal_zone0/temp || return 0
#	echo $(head -c 2 /sys/class/thermal/thermal_zone0/temp)C
	sensors | awk '/temp1/ {print $2}'
}

print_bat(){
	hash acpi || return 0
	onl="$(grep "on-line" <(acpi -V))"
	charge="$(awk '{ sum += $1 } END { print sum }' /sys/class/power_supply/BAT*/capacity)"
	if test -z "$onl"
	then
		# suspend when we close the lid
		#systemctl --user stop inhibit-lid-sleep-on-battery.service
		echo -e "${charge}"
	else
		# On mains! no need to suspend
		#systemctl --user start inhibit-lid-sleep-on-battery.service
		echo -e "${charge}"
	fi
}

print_date(){
#	echo $(date "+%a %m-%d %T%:::z") $(TZ=CET date "+ %H%:::z")
	echo $(date "+%d-%b-%y ⌚%T")
}

print_record(){
	# https://github.com/kaihendry/recordmydesktop2.0/
	test -f /tmp/r2d2 || return
	rp=$(cat /tmp/r2d2 | awk '{print $2}')
	size=$(du -h $rp | awk '{print $1}')
	echo " $size $(basename $rp)"
}

print_rec(){
	[ -f /tmp/screencast ] && echo "⏺️Rec"
}

while true
do
#	xsetroot -name "$(print_mem) $(print_network) $(print_temp) $(print_wifi) $(print_bat) $(print_record) $(print_date)"
	xsetroot -name "$(print_rec) ⌨ $(print_layout) $(print_mem) $(print_cpu) $(print_temp) $(print_hdd) "⚡"$(print_bat)% $(print_date)"
	sleep 1
done

