#!/bin/bash

#IN="eDP"
IN="LVDS1"
#EXT="HDMI-A-0"
EXT="DP1"

if (xrandr | grep "$EXT connected"); then
    xrandr --output $IN --off --output $EXT --auto --set TearFree on
else
    xrandr --output $EXT --off --output $IN --auto --set TearFree on
fi
