#!/bin/bash
sleep 0.2
#import png:- | xclip -selection c -t image/png
export filename=/tmp/screenshot-$(date +%F_%T).png; import png:$filename ;xclip -selection clipboard -target image/png -filter < $filename &>/dev/null

