#!/bin/bash

start_screencast(){
	touch /tmp/screencast && sleep 0.5s && refbar
	ffmpeg -y -f x11grab -framerate 60 -s "$(xdpyinfo | awk '/dimensions/ {print $2;}')" -i "$DISPLAY" -f alsa -i default -c:v h264 -crf 0 -preset ultrafast -r 30 -c:a aac "$HOME/Videos/screencast-$(date '+%y%m%d-%H%M-%S').mp4" &
	echo $! > /tmp/recordingpid
}


stop_screencast(){
	rm -f /tmp/screencast && refbar
	recpid="$(cat /tmp/recordingpid)"
    # kill with SIGTERM, allowing finishing touches.
    kill -15 "$recpid"
    rm -f /tmp/recordingpid
    # even after SIGTERM, ffmpeg may still run, so SIGKILL it.
    sleep 3
    kill -9 "$recpid"
	exit
}


[ -f /tmp/screencast ] && stop_screencast 
start_screencast

