#!/bin/bash
pstree | grep "unison" | grep -v "grep" &> /dev/null || /usr/bin/unison 

# Check if the previous command failed
if [ $? -ne 0 ]; then
	/usr/bin/dunstify -u critical "SyncUnison Failure" "The script failed at\n$(date)"
fi
