#!/bin/bash

VIDEO=${1}
    FILENAME=${VIDEO%.*}


$(which ffmpeg) -y -i "$VIDEO" -f avi -r 29.97 \
          -vcodec libxvid -vtag xvid \
          -vf scale=1920:1080 -b:v 1500k -qmin 3 -qmax 8 -bufsize 4096 \
          -mbd 2 -bf 2 -trellis 1 -flags +aic -cmp 2 -subcmp 2 -g 300 \
          -acodec libmp3lame -ar 48000 -ab 128k -ac 2 \
          "${FILENAME}"_edited.avi