# alacritty.toml
[selection]
save_to_clipboard = true

[mouse]
bindings = [
  { mouse = "Right", action = "PasteSelection" }
]

# ── Шрифт ───────────────────────────────────────────────────────
[font]
# Размер (скопируйте из st-конфига, например 12.0)
size = 11

# Основной нормальный стиль
[font.normal]
# Замените на имя вашего шрифта без указания размера
family = "JetBrains Mono"
style  = "Regular"

# (Опционально) если в st у вас есть жирный и/или курсив:
[font.bold]
family = "JetBrains Mono"
style  = "Bold"

[font.italic]
family = "JetBrains Mono"
style  = "Italic"

[font.bold_italic]
family = "JetBrains Mono"
style  = "Bold Italic"


# ── Окно ────────────────────────────────────────────────────────
[window]
padding = { x = 3, y = 2 }
# нежёсткая прозрачность всего окна
opacity = 0.90


# ── Цвета ───────────────────────────────────────────────────────
# Colors (Gruvbox dark)

# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
#background = '#282828'
background = '#32302f'
# soft contrast background = = '#32302f'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'
